export const SOCKET_CONNECT = 'SOCKET::CONNECT'
export const SOCKET_DISCONNECT = 'SOCKET::DISCONNECT'
export const SOCKET_MESSAGE_RECEIVED = 'SOCKET::MESSAGE_RECEIVED'
export const SOCKET_SEND_MESSAGE = 'SOCKET::SEND_MESSAGE'